---

- name: set timezone to UTC
  timezone:
    name: UTC

- name: Make sure Ansible local facts directory exists
  file:
    dest: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: ensure needed packages are installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - unzip
    - python-dns
    - bind-utils

- name: 'add subdomains to /etc/hosts'
  template:
    src: templates/hosts.j2
    dest: /etc/hosts

- name: 'ensure unneeded services are stoped and disabled'
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - rpcbind
    - rpcbind.socket
