---

- hosts: monitoring
  gather_facts: true
  become: yes
  remote_user: sysadm
  environment:
    NETRC: ''
  roles:
    - role: common
    - role: dnsmasq
    - role: resolv
    - role: openldap
    - role: mariadb
    - role: icinga2
    - role: php-fpm
    - role: nginx
    - role: icingaweb2
    - role: grafana
    - role: beanstalkd
    - role: redis
    - role: go-carbon
    - role: carbonapi
    - role: rest-service
    - role: service-discovery
    - role: data-collector
    - role: carbon-client
    - role: grafana-client

# - hosts: satellite
#   gather_facts: true
#   become: yes
#   remote_user: sysadm
#   environment:
#     NETRC: ''
#   roles:
#     # - role: common
#     # - role: dnsmasq
#     # - role: resolv
#     - role: icinga2
