---

- hosts: monitoring
  gather_facts: true
  become: yes
  remote_user: sysadm
  environment:
    NETRC: ''
  roles:
    - role: common
    - role: openldap
    - role: dnsmasq
    - role: resolv
    - role: beanstalkd
    - role: redis
    - role: mariadb
    - role: go-carbon
    - role: carbonapi
    - role: nginx
    - role: grafana
    - role: rest-service
    - role: service-discovery
    - role: data-collector
    - role: carbon-client
    - role: grafana-client

#     - role: firewalld
#     - role: trickster
#     - role: prometheus
#     - role: grafana_selinux
