---

- hosts: monitoring
  # gather_facts: true
  become: yes
  remote_user: sysadm
  environment:
    NETRC: ''
  roles:
    - role: common
    # - role: dnsmasq
    # - role: resolv
    - role: beanstalkd
    # - role: redis
    # - role: mariadb
    # - role: nginx
    - role: rest-service
    - role: service-discovery
#     - role: firewalld
#
#     - role: trickster
#     - role: prometheus
#     - role: grafana
#     - role: grafana_selinux
#     - role: nginx
