---

- hosts: monitoring
  gather_facts: true
  become: yes
  remote_user: sysadm
  environment:
    NETRC: ''
  roles:
    - role: common
    - role: snakeoil
    - role: dnsmasq
    - role: resolv
    - role: mariadb
    - role: openldap
    - role: nginx
    - role: beanstalkd
    - role: redis
    - role: go-carbon
    - role: carbonapi
    - role: rest-service
    - role: service-discovery
    - role: data-collector
    - role: carbon-client
    - role: grafana-client
    - role: icinga-client
    - role: php-fpm
    - role: icingaweb2
    - role: icinga2
    - role: grafana

- hosts: satellite
  gather_facts: true
  become: yes
  remote_user: sysadm
  environment:
    NETRC: ''
  roles:
    - role: icinga2
      vars:
        icinga2_mode: satellite
        icinga2_server: monitoring.cm.local
        icinga2_master: icinga.cm.local
        icinga2_certificate_cn: "{{ ansible_fqdn }}"
