
- name: resolv
  src: https://github.com/ahuffman/ansible-resolv.git
  version: 1.3.1

- name: dnsmasq
  src: https://github.com/bertvv/ansible-dnsmasq.git
  version: v2.1.0

- name: mariadb
  src: https://github.com/bodsch/ansible-role-mariadb.git
  version: feature/support-debian

- name: nginx
  src: https://github.com/geerlingguy/ansible-role-nginx.git
  version: 2.7.0

- name: redis
  src: https://github.com/geerlingguy/ansible-role-redis.git
  version: 1.6.0

- name: beanstalkd
  src: https://gitlab.com/coremedia-monitoring/ansible-beanstalkd.git
  scm: git
  version: master

- name: rest-service
  src: https://gitlab.com/coremedia-monitoring/ansible-rest-service.git
  scm: git
  version: master

- name: service-discovery
  src: https://gitlab.com/coremedia-monitoring/ansible-service-discovery.git
  scm: git
  version: master
