
- name: mariadb
  src: https://github.com/bodsch/ansible-role-mariadb.git
  version: feature/support-debian

- name: redis
  src: https://github.com/geerlingguy/ansible-role-redis.git
  version: 1.6.0

- name: beanstalkd
  src: https://gitlab.com/coremedia-monitoring/ansible-beanstalkd.git
  scm: git
  version: master

- name: rest-service
  src: https://gitlab.com/coremedia-monitoring/ansible-rest-service.git
  scm: git
  version: master

- name: service-discovery
  src: https://gitlab.com/coremedia-monitoring/ansible-service-discovery.git
  scm: git
  version: master
