---

- hosts: delivery
  gather_facts: true
  become: yes
  remote_user: sysadm
  roles:
    - dnsmasq
    - role: cae-live
      vars:
        - instances: 2
    - role: nginx
    - role: overview

- hosts: frontend
  gather_facts: true
  become: yes
  remote_user: sysadm
  roles:
#    - role: cm-licenses
    - role: master-live-server_tools
    - role: replication-live-server_tools
    - role: caefeeder_tools
      vars:
        - coremedia_application_name: caefeeder-live-tools
        - application_database:
            name: cm_caefeeder
            user: cm_caefeeder
            password: cm_caefeeder
    - role: solr
    - role: master-live-server
    - role: replication-live-server
    - role: caefeeder-live


- hosts: backend
  gather_facts: true
  become: yes
  remote_user: sysadm
  roles:
    - ulimit
    - dnsmasq
#    - role: cm-licenses
    - role: theme-importer_tools
    - role: content-management-server_tools
    - role: workflow-server_tools
    - role: caefeeder_tools
      vars:
        - coremedia_application_name: caefeeder-preview-tools
        - application_database:
            name: cm_mcaefeeder
            user: cm_mcaefeeder
            password: cm_mcaefeeder
    - role: solr
    - role: nginx
    - role: content-management-server
    - role: workflow-server
    - role: caefeeder-preview
    - role: content-feeder
    - role: elastic-worker
    - role: user-changes
    - role: studio
    - role: cae-preview

