---

# licenses
#
- hosts: frontend,backend,delivery
  gather_facts: true
  become: yes
  remote_user: sysadm
  roles:
    - role: license-manager

# frontend content services
#  - solr
#  - master-live-server
#  - caefeeder-live
#
- hosts: frontend
  gather_facts: true
  become: yes
  remote_user: sysadm
  roles:
    - role: master-live-server_tools
    - role: caefeeder_tools
      vars:
        - coremedia_application_name: caefeeder-live-tools
        - application_database:
            name: cm_caefeeder
            user: cm_caefeeder
            password: cm_caefeeder
    - role: solr
    - role: master-live-server
    - role: caefeeder-live

# backend content services
#  - solr
#  - content-management-server
#  - workflow-server
#  - caefeeder-preview
#  - content-feeder
#  - elastic-worker
#  - user-changes
#  - studio
#  - cae-preview
#  - nginx
#
- hosts: backend
  gather_facts: true
  become: yes
  remote_user: sysadm
  roles:
    - role: theme-importer_tools
    - role: content-management-server_tools
    - role: workflow-server_tools
    - role: caefeeder_tools
      vars:
        - coremedia_application_name: caefeeder-preview-tools
        - application_database:
            name: cm_mcaefeeder
            user: cm_mcaefeeder
            password: cm_mcaefeeder
    - role: solr
    - role: content-management-server
    - role: workflow-server
    - role: content-import
    - role: caefeeder-preview
    - role: content-feeder
    - role: elastic-worker
    - role: user-changes
    - role: studio
    - role: cae-preview
    - role: snakeoil
    # - role: nginx

# delivery services
#  - replication-live-server
#  - cae-live
#  - nginx
#
- hosts: delivery
  gather_facts: true
  become: yes
  remote_user: sysadm
  roles:
    - role: replication-live-server_tools
    - role: replication-live-server
    - role: cae-live
      vars:
        - instances: 2
    - role: snakeoil
    - role: nginx
    - role: overview
