---

- hosts: delivery,frontend,backend
  gather_facts: true
  become: yes
  remote_user: sysadm
  roles:
    - role: coremedia-tomcat

- hosts: backend
  gather_facts: true
  become: yes
  remote_user: sysadm
  roles:
    - role: coremedia-cms
