---

- hosts: delivery,frontend,backend
  gather_facts: true
  become: yes
  remote_user: sysadm
  roles:
    - role: tomcat

- hosts: backend
  gather_facts: true
  become: yes
  remote_user: sysadm
  roles:
    - role: content-management-server
