---

# prepare all coremedia machines
- hosts: delivery,frontend,backend
  gather_facts: true
  become: yes
  remote_user: sysadm
  environment:
    NETRC: ''
  roles:
    - role: common
    - role: firewalld
    - role: coretto
    - role: chef-client
    #- role: coremedia-artifacts
