---
- hosts: all
  gather_facts: true
  become: yes
  remote_user: sysadm
  environment:
    NETRC: ''
  roles:
    - role: common
    - role: firewalld
    - role: ulimit
    - role: dnsmasq

# prepare all coremedia machines
- hosts: delivery,frontend,backend
  gather_facts: true
  become: yes
  remote_user: sysadm
  environment:
    NETRC: ''
  roles:
    - role: coretto
    - role: tomcat

# prepare the databases
- hosts: database
  gather_facts: true
  become: yes
  remote_user: sysadm
  roles:
    - role: mongodb
    - role: mariadb
