---

# prepare all coremedia machines
- hosts: delivery,frontend,backend
  gather_facts: true
  become: yes
  remote_user: sysadm
  roles:
    #- role: common
    #- role: firewalld
    #- role: coretto
    #- role: chef-client
    - role: coremedia-artifacts
