- name: dnsmasq
  src: https://github.com/bertvv/ansible-dnsmasq.git
  version: v2.1.0
- name: mariadb
  src: https://github.com/bertvv/ansible-role-mariadb.git
  version: v3.0.0
- name: sshd
  src: https://github.com/willshersystems/ansible-sshd.git
  version: v0.8.0
- name: mongodb
  src: https://github.com/UnderGreen/ansible-role-mongodb.git
  version: v2.6.0
- name: redis
  src: https://github.com/geerlingguy/ansible-role-redis.git
  version: 1.6.0
- name: firewalld
  src: https://github.com/oasis-roles/firewalld.git
  version: master
- name: grafana
  src: https://github.com/cloudalchemy/ansible-grafana.git
  version: 0.14.2
- name: node_exporter
  src: https://github.com/cloudalchemy/ansible-node-exporter.git
  version: 0.14.0
- name: prometheus
  src: https://github.com/cloudalchemy/ansible-prometheus.git
  version: 2.11.0
- name: nginx
  src: https://github.com/geerlingguy/ansible-role-nginx.git
  version: 2.6.1

- name: coretto
  src: https://github.com/bodsch/ansible-coretto-java.git
  scm: git
  version: 1.0.1
- name: chef-client
  src: https://gitlab.com/bodsch/ansible-coremedia-chef-client.git
  scm: git
  version: master
- name: coremedia-artifacts
  src: https://gitlab.com/bodsch/ansible-coremedia-artifacts.git
  scm: git
  version: master
- name: coremedia-deployment
  src: https://gitlab.com/bodsch/ansible-coremedia-deployment.git
  scm: git
  version: master
- name: grafana_selinux
  src: https://gitlab.com/bodsch/ansible-grafana-selinux.git
  scm: git
  version: 1.0.0
- name: trickster
  src: https://gitlab.com/bodsch/ansible-trickster.git
  scm: git
  version: 1.0.1

- name: tomcat
  src: https://gitlab.com/ansible-coremedia/tomcat.git
  scm: git
  version: 1.0.0
- name: content-management-server_tools
  src: https://gitlab.com/ansible-coremedia/content-management-server_tools.git
  scm: git
  version: 1.0.0
- name: master-live-server_tools
  src: https://gitlab.com/ansible-coremedia/master-live-server_tools.git
  scm: git
  version: 1.0.0
- name: replication-live-server_tools
  src: https://gitlab.com/ansible-coremedia/replication-live-server_tools.git
  scm: git
  version: 1.0.0
- name: workflow-server_tools
  src: https://gitlab.com/ansible-coremedia/workflow-server_tools.git
  scm: git
  version: 1.0.0






- name: content-management-server
  src: https://gitlab.com/ansible-coremedia/content-management-server.git
  scm: git
  version: 1.1.0
- name: master-live-server
  src: https://gitlab.com/ansible-coremedia/master-live-server.git
  scm: git
  version: 1.0.0
- name: replication-live-server
  src: https://gitlab.com/ansible-coremedia/replication-live-server.git
  scm: git
  version: 1.0.0
- name: workflow-server
  src: https://gitlab.com/ansible-coremedia/workflow-server.git
  scm: git
  version: 1.0.0
